### ISSUE TITLE
Compilation on mac apple silicon

### ISSUE THREAD

**Issue by ghost** [amchess/Alexander#1]
### Describe the issue

after compilation with the command make build ARCH=apple-silicon there is an error 
./types.h:538:9: error: no type named 'size_t' in namespace 'std'; did you mean simply 'size_t'?

### Expected behavior

add the #include with cstddef in the file types.h

### Operating system

MacOS

### Alexander version

Alexander 1.2

**Comment by ghost** [comment]
include <cstddef>

**Comment by Ruyter64** [comment]
you must add the stddef like for cstdint in the file types.h
