### ISSUE TITLE
Alexander 1.2 Linux executables are actually ShashChess 35.2 Linux executables

### ISSUE THREAD

**Issue by tonymokonen** [amchess/Alexander#3]
### Describe the issue

The Alexander 1.2 Linux.zip file is identical to the ShashChess 35.2 Linux.zip file.

### Expected behavior

Expected behavior is obvious in this case.

### Operating system

Linux

### Alexander version

Alexander 1.2

**Comment by amchess** [comment]
Done.
Thanks!
