### ISSUE TITLE
Managing people's access to your organization with roles

### ISSUE THREAD

**Issue by ghost** [amchess/Alexander#6]
![image](https://github.com/user-attachments/assets/b959dc99-9054-4aa7-a969-0580abdf9a86)

Unfortunately, despite many messages we sent, we could not take back ownership of @stockfish-NNUE.
@amchess I'd never expected you to remove us from my organization, and I had to decide what to do. 
Thank you for the good times, true friendship and unforgettable memories of the past year.
We left this organization. I hope you can manage it alone.
Good Bye!

**Comment by EarlyEdition** [comment]
Hi Andera,

I confirm that this organization belongs to me and that I have lost access to the repositories due to the deletion of my account. 

Please invite me as an owner or change @KasparovChess's role to owner so that he can invite me to the organization again.

Best wishes!

**Comment by KasparovChess** [comment]
@amchess, Unfortunately, despite many messages we sent, I could not take back ownership of the organization.
I never understood your reason for not transferring the ownership.
Anyway, We left this organization. I hope you can manage it alone.
Good Bye!

**Comment by EarlyEdition** [comment]
I've sent a message to GitHub:

https://github.com/orgs/community/discussions/138061
